export const AUCTION_ABI = [
  // Events
  {
    type: 'event',
    name: 'AuctionCreated',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'auctionType', type: 'uint8', indexed: false },
      { name: 'startPrice', type: 'uint256', indexed: false },
      { name: 'endPrice', type: 'uint256', indexed: false },
      { name: 'startTime', type: 'uint256', indexed: false },
      { name: 'endTime', type: 'uint256', indexed: false },
      { name: 'title', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BidPlaced',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'bidder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionSettled',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'winner', type: 'address', indexed: true },
      { name: 'finalPrice', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionCancelled',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AuctionExtended',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'newEndTime', type: 'uint256', indexed: false },
      { name: 'extensionCount', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SealedBidCommitted',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'bidder', type: 'address', indexed: true },
      { name: 'commitment', type: 'bytes32', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SealedBidRevealed',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'bidder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'PhaseTransition',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'fromPhase', type: 'uint8', indexed: false },
      { name: 'toPhase', type: 'uint8', indexed: false },
      { name: 'timestamp', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'BundleCreated',
    inputs: [
      { name: 'auctionId', type: 'uint256', indexed: true },
      { name: 'itemCount', type: 'uint256', indexed: false },
      { name: 'totalValue', type: 'uint256', indexed: false },
    ],
  },
  // Read functions
  {
    type: 'function',
    name: 'getAuction',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [{
      type: 'tuple',
      components: [
        { name: 'id', type: 'uint256' },
        { name: 'seller', type: 'address' },
        { name: 'auctionType', type: 'uint8' },
        { name: 'phase', type: 'uint8' },
        { name: 'startPrice', type: 'uint256' },
        { name: 'endPrice', type: 'uint256' },
        { name: 'currentBid', type: 'uint256' },
        { name: 'highestBidder', type: 'address' },
        { name: 'startTime', type: 'uint256' },
        { name: 'endTime', type: 'uint256' },
        { name: 'revealDeadline', type: 'uint256' },
        {
          name: 'config',
          type: 'tuple',
          components: [
            { name: 'antiSnipeEnabled', type: 'bool' },
            { name: 'extensionThreshold', type: 'uint256' },
            { name: 'extensionDuration', type: 'uint256' },
            { name: 'maxExtensions', type: 'uint256' },
            { name: 'currentExtensions', type: 'uint256' },
          ],
        },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string' },
        { name: 'imageUrl', type: 'string' },
        { name: 'paymentToken', type: 'address' },
        { name: 'preferredCurrency', type: 'address' },
        { name: 'noAutoConvert', type: 'bool' },
      ],
    }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveAuctionIds',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getActiveAuctionCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getCurrentPrice',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextAuctionId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSealedBidders',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'auctionWatcherCount',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userTemplateCount',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'userTemplates',
    inputs: [
      { name: '', type: 'address' },
      { name: '', type: 'uint256' },
    ],
    outputs: [{
      type: 'tuple',
      components: [
        { name: 'name', type: 'string' },
        { name: 'auctionType', type: 'uint8' },
        { name: 'startPrice', type: 'uint256' },
        { name: 'endPrice', type: 'uint256' },
        { name: 'duration', type: 'uint256' },
        {
          name: 'config',
          type: 'tuple',
          components: [
            { name: 'antiSnipeEnabled', type: 'bool' },
            { name: 'extensionThreshold', type: 'uint256' },
            { name: 'extensionDuration', type: 'uint256' },
            { name: 'maxExtensions', type: 'uint256' },
            { name: 'currentExtensions', type: 'uint256' },
          ],
        },
        { name: 'usageCount', type: 'uint256' },
        { name: 'isPublic', type: 'bool' },
      ],
    }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserWatchlist',
    inputs: [{ name: '_user', type: 'address' }],
    outputs: [{ name: '', type: 'uint256[]' }],
    stateMutability: 'view',
  },
  // Write functions
  {
    type: 'function',
    name: 'createDutchAuction',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_endPrice', type: 'uint256' },
      { name: '_durationSeconds', type: 'uint256' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_imageUrl', type: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createDutchAuctionWithToken',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_endPrice', type: 'uint256' },
      { name: '_durationSeconds', type: 'uint256' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_imageUrl', type: 'string' },
      { name: '_paymentToken', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createEnglishAuction',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_durationSeconds', type: 'uint256' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_imageUrl', type: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createEnglishAuctionWithToken',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_durationSeconds', type: 'uint256' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_imageUrl', type: 'string' },
      { name: '_paymentToken', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createSealedBidAuction',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_biddingDuration', type: 'uint256' },
      { name: '_revealDuration', type: 'uint256' },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
      { name: '_imageUrl', type: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createBundleAuction',
    inputs: [
      { name: '_startPrice', type: 'uint256' },
      { name: '_duration', type: 'uint256' },
      {
        name: '_items',
        type: 'tuple[]',
        components: [
          { name: 'tokenContract', type: 'address' },
          { name: 'tokenId', type: 'uint256' },
          { name: 'amount', type: 'uint256' },
          { name: 'tokenType', type: 'uint8' },
        ],
      },
      { name: '_title', type: 'string' },
      { name: '_description', type: 'string' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'createPriceAlert',
    inputs: [
      { name: '_auctionId', type: 'uint256' },
      { name: '_targetPrice', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addToWatchlist',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'removeFromWatchlist',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'saveTemplate',
    inputs: [{
      name: '_template',
      type: 'tuple',
      components: [
        { name: 'name', type: 'string' },
        { name: 'auctionType', type: 'uint8' },
        { name: 'startPrice', type: 'uint256' },
        { name: 'endPrice', type: 'uint256' },
        { name: 'duration', type: 'uint256' },
        {
          name: 'config',
          type: 'tuple',
          components: [
            { name: 'antiSnipeEnabled', type: 'bool' },
            { name: 'extensionThreshold', type: 'uint256' },
            { name: 'extensionDuration', type: 'uint256' },
            { name: 'maxExtensions', type: 'uint256' },
            { name: 'currentExtensions', type: 'uint256' },
          ],
        },
        { name: 'usageCount', type: 'uint256' },
        { name: 'isPublic', type: 'bool' },
      ],
    }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'bid',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'bidWithToken',
    inputs: [
      { name: '_auctionId', type: 'uint256' },
      { name: '_token', type: 'address' },
      { name: '_amount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'commitBid',
    inputs: [
      { name: '_auctionId', type: 'uint256' },
      { name: '_commitment', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'revealBid',
    inputs: [
      { name: '_auctionId', type: 'uint256' },
      { name: '_amount', type: 'uint256' },
      { name: '_secret', type: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'settleAuction',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelAuction',
    inputs: [{ name: '_auctionId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;
